version: '3'
services:

    pt-pg-db:
        image: postgres:9.6.3
        container_name: pt-pg-db
        restart: on-failure
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=pt-pg-db
            - PGDATA=/pt/postgresql/data/pgdata
        volumes:
            - pt-pg-db:/pt/postgresql/data
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./docker-scripts-initdb.d:/docker-scripts-initdb.d
        ports:
            - "5432:5432"

volumes:
    pt-pg-db: {}

networks:
  default:
    external:
      name: pt