version: '3'
services:

    pt-es-db:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
      container_name: pt-es-db
      volumes:
        - pt-es-db:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      environment:
        - "ES_JAVA_OPTS=-Xms${es_memory} -Xmx${es_memory}"
        - bootstrap.memory_lock=true
        - http.host=0.0.0.0
        - transport.host=127.0.0.1
      restart: on-failure
      ulimits:
        nproc: 65536
        nofile:
          soft: 65536
          hard: 65536
        memlock:
          soft: -1
          hard: -1
      cap_add:
        - IPC_LOCK

volumes:
  pt-es-db: {}

networks:
  default:
    external:
      name: pt